app/models.py
import sqlite3
from contextlib import closing
from flask_sqlalchemy import SQLAlchemy
import os
from flask import Flask
from . import db


class Role(db.Model):
    __tablename__ = 'roles'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)

    def __repr__(self):
        return '<Role %r' % self.name


class User(db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), unique=True)
    password = db.Column(db.String(64))

    def __repr__(self):
        return '<User %r>' % self.username


class Entry(db.Model):
    ___tablename__ = 'entries'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.Text,nullable=False)
    text = db.Column(db.Text)

    def __repr__(self):
        return '<Entry %r>' % self.title

app/__init__.py
from flask import Flask
import config
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
import os
import app


app = Flask(__name__)
db = SQLAlchemy(app)
bootstrap = Bootstrap(app)
db.init_app(app)
db.create_all()

def create_app():
    app.config.from_object(config)
    basedir = os.path.abspath(os.path.dirname(__file__))
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///'+os.path.join(basedir, 'data.sqlite')
    app.config['SQLALCHEMY_COMMIT_ON_TEARDOWN'] = True
    # import blueprint here
    from main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . import views

app/main/views.py
from . import main
from flask import g,render_template,flash,session,abort,request,redirect,url_for
from ..models import User,Entry,db


@main.before_request
def before_request():
    pass


@main.teardown_request
def teardown_request(exception):
    pass

@main.route('/')
def show_entries():
    test = Entry.query.all()
    print test
    entries = Entry.query.all()
    return render_template('show_entries.html', entries=entries)


@main.route('/add', methods=['POST'])
def add_entry():
    if not session.get('logged_in'):
        abort(401)
    newentry = Entry(title=request.form['title'], text=request.form['text'])
    db.session.add_all([newentry])
    db.session.commit()
    flash('New entry was successfully posted')
    return redirect(url_for('main.show_entries'))


@main.route('/login', methods=['GET', 'POST'])
def login():
    error = None
    if request.method == 'POST':
        user = User.query.filter_by(username='admin').first()
        if user == None:
            error = 'Invalid username'
        elif request.form['password'] != user.password:
            error = 'Invalid password'
        else:
            session['logged_in'] = True
            flash('You were logged in')
            return redirect(url_for('main.show_entries'))
    return render_template('login.html', error=error)


@main.route('/logout')
def logout():
    session.pop('logged_in', None)
    flash('You were logged out')
    return redirect(url_for('main.show_entries'))

app/templates/layout.html
{% extends "bootstrap/base.html" %}
{% block title %}Blog{% endblock %}
{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle"
            data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Blog</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
               {% if not session.logged_in %}
                    <li><a href="{{ url_for('main.login') }}">log in</a></li>
              {% else %}
                    <li><a href="{{ url_for('main.logout') }}">log out</a></li>
              {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
{% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
{% endfor %}
{% block page_content %}
    {#这是正文内容#}
{% endblock %}
</div>
{% endblock %}

app/templates/login.html
{% extends "layout.html" %}
{% block page_content %}
    <div class="container">
        <div class="page-header">
              <h2>Login</h2>
              {% if error %}<p class=error><strong>Error:</strong> {{ error }}{% endif %}
              <form action="{{ url_for('main.login') }}" method=post>
                <dl>
                  <dt>Username:
                  <dd><input type=text name=username>
                  <dt>Password:
                  <dd><input type=password name=password>
                  <dd><input type=submit value=Login>
                </dl>
              </form>
        </div>
    </div>
{% endblock %}

app/templates/show_entries.html
{% extends "layout.html" %}
{% block page_content %}
    <div class="container">
        <div class="page-header">
            {% if session.logged_in %}
            <form action="{{ url_for('main.add_entry') }}" method=post class=add-entry>
              <dl>
                <dt>Title:
                <dd><input type=text size=30 name=title>
                <dt>Text:
                <dd><textarea name=text rows=5 cols=40></textarea>
                <dd><input type=submit value=Share>
              </dl>
            </form>
          {% endif %}
          <ul class=entries>
          {% for entry in entries %}
            <li><h2>{{ entry.title }}</h2>{{ entry.text|safe }}
          {% else %}
            <li><em>Unbelievable.  No entries here so far</em>
          {% endfor %}
          </ul>
        </div>
    </div>
{% endblock %}